// The six departments' construction/style fields, per the review doc.
// Keys must match server/routes/oms.routes.js's DEPARTMENT_REQUIRED_FIELDS
// exactly — a mismatch makes the server accept as complete what the UI
// never actually asked for, or block on a field the UI never shows.
export const DEPARTMENT_FIELDS = {
  suit: {
    label: 'Suit',
    note: 'Final collar measurements should be plus 1.5"/2" to the actual measurement.',
    fields: [
      { key: 'fabricColor', label: 'Fabric Color', required: true },
      { key: 'suitStyle', label: 'Suit Style', required: true },
      { key: 'gender', label: 'Gender', required: true },
      { key: 'lapelFabric', label: 'Lapel Fabric', required: true },
      { key: 'lapelStyle', label: 'Lapel Style', required: true },
      { key: 'lapelWidth', label: 'Lapel Width', required: true },
      { key: 'pocketStyle', label: 'Pocket Style', required: true },
      { key: 'ventStyle', label: 'Vent Style', required: true },
      { key: 'collarType', label: 'Collar Type', required: true },
      { key: 'sbDb', label: 'SB/DB', required: true },
      { key: 'sleeveType', label: 'Sleeve Type', required: true },
      { key: 'handKnitting', label: 'Hand Knitting', required: true },
      { key: 'buttonStyle', label: 'Button Style', required: true },
      { key: 'additionalInformation', label: 'Additional Information', required: false },
    ],
  },
  native: {
    label: 'Native',
    note: 'Chest pocket depth, 7". Chest pocket height should be plus 1.5" to the width. Final neck measurements should be plus 1.5" to the actual measurement.',
    fields: [
      { key: 'fabricColor', label: 'Fabric Color', required: true },
      { key: 'neckType', label: 'Neck Type', required: true },
      { key: 'length', label: 'Length', required: true },
      { key: 'sleeveType', label: 'Sleeve Type', required: true },
      { key: 'cuffType', label: 'Cuff Type', required: true },
      { key: 'chestPocketStyle', label: 'Chest Pocket Style', required: true },
      { key: 'collarType', label: 'Collar Type', required: true },
      { key: 'embroidery', label: 'Embroidery', required: true },
      { key: 'embroideryType', label: 'Embroidery Type', required: true },
      { key: 'collarButton', label: 'Collar Button', required: true },
      { key: 'twifLogo', label: 'Twif Logo', required: true },
      { key: 'buttonType', label: 'Button Type', required: true },
      { key: 'liningType', label: 'Lining Type', required: true },
      { key: 'collarSize', label: 'Collar Size', required: true },
      { key: 'longSleeveType', label: 'Long Sleeve Type', required: true },
      { key: 'slitType', label: 'Slit Type', required: true },
      { key: 'slitLiningType', label: 'Slit Lining Type', required: true },
      { key: 'sidePocket', label: 'Side Pocket', required: true },
      { key: 'cap', label: 'Cap', required: true },
      { key: 'capStyle', label: 'Cap Style', required: true },
      { key: 'additionalInformation', label: 'Additional Information', required: false },
    ],
  },
  shirts: {
    label: 'Shirts',
    note: 'Kids cuff must be button not cufflinks. Final collar measurements should be plus 1.5" to the actual measurement.',
    fields: [
      { key: 'fabricColor', label: 'Fabric Color', required: true },
      { key: 'gender', label: 'Gender', required: true },
      { key: 'buttonHoleStand', label: 'Button Hole Stand', required: true },
      { key: 'sleeveType', label: 'Sleeve Type', required: true },
      { key: 'longSleeveType', label: 'Long Sleeve Type', required: true },
      { key: 'cuffStyle', label: 'Cuff Style', required: true },
      { key: 'cuffType', label: 'Cuff Type', required: true },
      { key: 'collar', label: 'Collar', required: true },
      { key: 'collarSize', label: 'Collar Size', required: true },
      { key: 'embroidery', label: 'Embroidery', required: true },
      { key: 'embroideryType', label: 'Embroidery Type', required: true },
      { key: 'collarThickness', label: 'Collar Thickness', required: true },
      { key: 'shirtEnd', label: 'Shirt End', required: true },
      { key: 'beadingEmbellishment', label: 'Beading/Embellishment', required: true },
      { key: 'buttonType', label: 'Button Type', required: true },
      { key: 'additionalInformation', label: 'Additional Information', required: false },
    ],
  },
  agbada: {
    label: 'Agbada',
    note: '',
    fields: [
      { key: 'fabricColor', label: 'Fabric Color', required: true },
      { key: 'agbadaStyle', label: 'Agbada Style', required: true },
      { key: 'sleeveType', label: 'Sleeve Type', required: true },
      { key: 'embroideryType', label: 'Embroidery Type', required: true },
      { key: 'sleeveLining', label: 'Sleeve Lining', required: true },
      { key: 'additionalInformation', label: 'Additional Information', required: false },
    ],
  },
  design: {
    label: 'Design',
    note: '',
    fields: [
      { key: 'fabricType', label: 'Fabric Type', required: true },
      { key: 'fabricColor', label: 'Fabric Color', required: true },
      { key: 'threadColor', label: 'Thread Color', required: true },
      { key: 'embroideryLength', label: 'Embroidery Length', required: true },
      { key: 'danshiki', label: 'Danshiki', required: true },
      { key: 'trouser', label: 'Trouser', required: true },
      { key: 'cap', label: 'Cap', required: true },
      { key: 'additionalInformation', label: 'Additional Information', required: false },
    ],
  },
  pants: {
    label: 'Pants',
    note: 'Trousers for kids (age 0-13) must have elastic on the band at the back.',
    fields: [
      { key: 'fabricColor', label: 'Fabric Color', required: true },
      { key: 'pantType', label: 'Pant Type', required: true },
      { key: 'gender', label: 'Gender', required: true },
      { key: 'pleats', label: 'Pleats', required: true },
      { key: 'bandStyle', label: 'Band Style', required: true },
      { key: 'bandExtension', label: 'Band Extension', required: true },
      { key: 'bandSize', label: 'Band Size', required: true },
      { key: 'beltlessType', label: 'Beltless Type', required: true },
      { key: 'sideStripe', label: 'Side Stripe', required: true },
      { key: 'backPocketStyle', label: 'Back Pocket Style', required: true },
      { key: 'additionalInformation', label: 'Additional Information', required: false },
    ],
  },
};
